// SPDX-License-Identifier: GPL-3.0-only
//! Host-native render rig proving the mechanism `meshcadet-emoji-mono-
//! glyph-legibility`'s colorization step (Scope item 4) actually relies on:
//! Slint's `SoftwareRenderer` blends a registered `BitmapFont` glyph's alpha
//! mask with the OWNING `Text` element's own `color` property, so two
//! `Text` runs that share the SAME globally-registered font can still paint
//! DIFFERENT colors, as long as each fixed-UI-emoji call site is its own
//! `Text` (never merged with other characters into one run).
//!
//! # Why a hand-built minimal font, not the real `MeshCadetEmoji` font
//!
//! Same rationale as `emoji_blank_cell_probe.rs`'s own module doc: the real
//! bundled font is generated by a `firmware/`-only build step this
//! host-workspace crate has no path to. What needs proving here is the
//! RENDERER's per-`Text`-element color compositing, not the specific
//! rasterized pixels of any one production glyph — so this rig hand-builds
//! a tiny `BitmapFont` with three mapped glyphs, one per fixed-UI-emoji call
//! site this mission actually colorized (`pin_entry.rs`'s 🔐, `gps_status.rs`'s
//! 📍, `compose.rs`'s 😀 picker toggle), each fully opaque (alpha 0xFF) so a
//! single-pixel sample rendered over a pure-black background reads back as
//! EXACTLY that `Text`'s own `color` — no partial-alpha blending arithmetic
//! to account for.
//!
//! A second, independent case (`half_alpha`) uses a half-opaque glyph (alpha
//! 0x80) to prove the SAME per-`Text`-element coloring holds at a partial
//! alpha too — i.e. an antialiased glyph edge (or, on the real emoji face,
//! any pixel the alpha-gamma boost lifted from washed-out gray toward solid
//! ink) still composites against its OWN `Text`'s color, not some shared/
//! global tint.

use std::rc::Rc;
use std::time::{Duration, Instant};

use i_slint_core::graphics::{BitmapFont, BitmapGlyph, BitmapGlyphs, CharacterMapEntry};
use i_slint_core::slice::Slice;
use slint::platform::software_renderer::{MinimalSoftwareWindow, RepaintBufferType, Rgb565Pixel};
use slint::platform::{Platform, PlatformError, WindowAdapter};
use slint::PhysicalSize;

pub const WIDTH: u32 = 96;
pub const HEIGHT: u32 = 16;

/// The one pixel size this probe font is rasterised at.
const PROBE_PX: i16 = 16;

// glyph_index 0 = fully opaque (alpha 0xFF) — stands in for 🔐/📍/😀's
// solid-ink pixels. glyph_index 1 = half-opaque (alpha 0x80) — stands in
// for an antialiased edge / a pre-gamma-boost washed-out pixel. Both glyphs
// map to distinct codepoints below so a test can select either shape at
// each of the three probe positions independently.
static GLYPHS_16: [BitmapGlyph; 2] = [
    BitmapGlyph {
        x: 0,
        y: 0,
        width: PROBE_PX,
        height: PROBE_PX,
        x_advance: PROBE_PX * 64,
        data: Slice::from_slice(&[0xFFu8; (PROBE_PX * PROBE_PX) as usize]),
    },
    BitmapGlyph {
        x: 0,
        y: 0,
        width: PROBE_PX,
        height: PROBE_PX,
        x_advance: PROBE_PX * 64,
        data: Slice::from_slice(&[0x80u8; (PROBE_PX * PROBE_PX) as usize]),
    },
];

static GLYPH_SETS: [BitmapGlyphs; 1] = [BitmapGlyphs {
    pixel_size: PROBE_PX,
    glyph_data: Slice::from_slice(&GLYPHS_16),
}];

// Codepoint-sorted (required for `PixelFont::shape_text`'s binary search).
// 'F' (full-alpha stand-in) and 'H' (half-alpha stand-in) are plain ASCII
// so this probe's `Text.text` strings stay trivial to construct/read.
static CHAR_MAP: [CharacterMapEntry; 2] = [
    CharacterMapEntry {
        code_point: 'F',
        glyph_index: 0, // full alpha (0xFF)
    },
    CharacterMapEntry {
        code_point: 'H',
        glyph_index: 1, // half alpha (0x80)
    },
];

static PROBE_FONT: BitmapFont = BitmapFont {
    family_name: Slice::from_slice(b"EmojiColorProbe"),
    character_map: Slice::from_slice(&CHAR_MAP),
    units_per_em: PROBE_PX as f32,
    ascent: PROBE_PX as f32,
    descent: 0.0,
    x_height: (PROBE_PX / 2) as f32,
    cap_height: (PROBE_PX * 3 / 4) as f32,
    glyphs: Slice::from_slice(&GLYPH_SETS),
    weight: 400,
    italic: false,
    sdf: false,
};

slint::slint! {
    import { Theme } from "../../firmware/src/ui/theme.slint";

    // Three independent Text elements, one per probed fixed-UI-emoji call
    // site, EACH given that call site's real color (mono-glyph-legibility
    // mission): pin_entry.rs's 🔐 (Theme.warn), gps_status.rs's 📍
    // (Theme.ok), compose.rs's 😀 picker toggle (Theme.star-gold). No
    // `font-family:` set — same as every real screen: the globally
    // registered `BitmapFont` (registered BEFORE this component is
    // constructed, see `EmojiColorProbeFrame::new`) is what actually serves
    // these runs.
    export component EmojiColorProbeUi inherits Window {
        width: 96px;
        height: 16px;
        background: #000000;

        in property <string> lock_glyph: "F";
        in property <string> gps_glyph: "F";
        in property <string> picker_glyph: "F";

        Text {
            text: lock_glyph;
            font-size: 16px;
            color: Theme.warn;
            x: 0px;
            y: 0px;
        }
        Text {
            text: gps_glyph;
            font-size: 16px;
            color: Theme.ok;
            x: 32px;
            y: 0px;
        }
        Text {
            text: picker_glyph;
            font-size: 16px;
            color: Theme.star-gold;
            x: 64px;
            y: 0px;
        }
    }
}

struct EmojiColorProbePlatform {
    window: Rc<MinimalSoftwareWindow>,
    start: Instant,
}

impl Platform for EmojiColorProbePlatform {
    fn create_window_adapter(&self) -> Result<Rc<dyn WindowAdapter>, PlatformError> {
        Ok(self.window.clone())
    }

    fn duration_since_start(&self) -> Duration {
        self.start.elapsed()
    }
}

/// Render rig for the fixed-UI-emoji color-compositing probe.
///
/// # Panics
/// Panics if a Slint platform is already installed in this process — see
/// `emoji_blank_cell_probe.rs`'s identical note. Callers must ensure exactly
/// one [`EmojiColorProbeFrame::new`] runs per process.
pub struct EmojiColorProbeFrame {
    window: Rc<MinimalSoftwareWindow>,
    ui: EmojiColorProbeUi,
}

impl EmojiColorProbeFrame {
    pub fn new() -> Self {
        let window = MinimalSoftwareWindow::new(RepaintBufferType::ReusedBuffer);
        window.set_size(PhysicalSize::new(WIDTH, HEIGHT));
        slint::platform::set_platform(Box::new(EmojiColorProbePlatform {
            window: window.clone(),
            start: Instant::now(),
        }))
        .expect("Slint platform already set in this process");

        window.renderer().register_bitmap_font(&PROBE_FONT);

        let ui = EmojiColorProbeUi::new().expect("EmojiColorProbeUi::new");
        ui.show().expect("EmojiColorProbeUi::show");

        EmojiColorProbeFrame { window, ui }
    }

    /// Select the full-alpha ('F') or half-alpha ('H') glyph shape at each
    /// of the three probe positions independently.
    pub fn set_glyphs(&self, lock: &str, gps: &str, picker: &str) {
        self.ui.set_lock_glyph(lock.into());
        self.ui.set_gps_glyph(gps.into());
        self.ui.set_picker_glyph(picker.into());
    }

    /// Render one frame.
    pub fn render(&self) -> Vec<Rgb565Pixel> {
        slint::platform::update_timers_and_animations();
        self.window.request_redraw();

        let mut framebuffer = vec![Rgb565Pixel(0); (WIDTH * HEIGHT) as usize];
        let rendered = self.window.draw_if_needed(|renderer| {
            renderer.render(&mut framebuffer, WIDTH as usize);
        });
        assert!(
            rendered,
            "emoji color probe frame was not dirty — nothing painted"
        );
        framebuffer
    }
}

impl Default for EmojiColorProbeFrame {
    fn default() -> Self {
        Self::new()
    }
}

/// Convert a rendered RGB565 framebuffer to an `image::RgbImage` (RGB8) —
/// same conversion every other `ui_sim` render module duplicates locally.
pub fn framebuffer_to_rgb_image(
    framebuffer: &[Rgb565Pixel],
    width: u32,
    height: u32,
) -> image::RgbImage {
    let mut img = image::RgbImage::new(width, height);
    for (i, px) in framebuffer.iter().enumerate() {
        let r5 = (px.0 >> 11) & 0x1F;
        let g6 = (px.0 >> 5) & 0x3F;
        let b5 = px.0 & 0x1F;
        let r8 = ((r5 << 3) | (r5 >> 2)) as u8;
        let g8 = ((g6 << 2) | (g6 >> 4)) as u8;
        let b8 = ((b5 << 3) | (b5 >> 2)) as u8;
        let x = (i as u32) % width;
        let y = (i as u32) / width;
        img.put_pixel(x, y, image::Rgb([r8, g8, b8]));
    }
    img
}
