// SPDX-License-Identifier: GPL-3.0-only
//! Host-native render rig proving `protocol::emoji::normalize_inbound`
//! actually eliminates the "blank cell" defect on a REAL Slint render — not
//! just that the function's own host unit tests pass in isolation.
//!
//! # Why a hand-built minimal font, not the real `MeshCadetEmoji` font
//!
//! The real bundled font (`firmware/gen_emoji_font.c` → `$OUT_DIR/
//! emoji_font.rs`) is generated by a `firmware/`-only build step (shells out
//! to a compiled FreeType tool over the bundled TTFs) that this
//! host-workspace crate has no path to and should not grow one for — see
//! `ui_sim`'s own module doc for why `firmware/` cannot be pulled onto the
//! host at all. What actually needs proving here is the RENDERER mechanism
//! (`i-slint-renderer-software`'s `PixelFont::shape_text`, `platform.rs`'s
//! module doc), not the specific rasterized pixels of any one production
//! glyph — so this rig hand-builds a tiny `i_slint_core::graphics::
//! BitmapFont` with exactly two mapped characters (`X` and `❤`, `U+2764`)
//! at ONE pixel size, using the SAME internal types
//! `firmware/src/ui/platform.rs`'s `emoji_font` module registers
//! (`BitmapFont`/`BitmapGlyph`/`BitmapGlyphs`/`CharacterMapEntry` +
//! `register_bitmap_font`), and — critically — deliberately does NOT map
//! VS16 (`U+FE0F`), mirroring the real bundled font's actual gap (see
//! `protocol::emoji`'s module doc). `X` stands in for a second glyph in the
//! run so its LEFT EDGE position can be measured; the two glyphs are given
//! different alpha (heart fully opaque, `X` half-opaque) so a pixel scan can
//! tell exactly where one ends and the other begins without any grapheme
//! interpretation.
//!
//! # What "no blank cell" means, made measurable
//!
//! `PixelFont::shape_text` (`i-slint-renderer-software`) assigns an
//! UNMAPPED character `glyph_id: None` and an `x_advance` of a full
//! `pixel_size` — it still occupies a whole character cell of horizontal
//! space, just with nothing painted in it. Rendering the RAW wire text
//! "❤️X" (`U+2764 U+FE0F 'X'`) through this font therefore paints the heart
//! at columns `[0, 16)`, a `[16, 32)` gap of pure background (VS16 has no
//! entry in this font, exactly like the real one), and `X` starting at
//! column 32 — the live defect. Rendering the NORMALIZED text ("❤X", VS16
//! already stripped by `normalize_inbound`) paints the heart at `[0, 16)`
//! and `X` starting immediately at column 16 — no gap. The test asserts
//! exactly this pair of column positions.

use std::rc::Rc;
use std::time::{Duration, Instant};

use i_slint_core::graphics::{BitmapFont, BitmapGlyph, BitmapGlyphs, CharacterMapEntry};
use i_slint_core::slice::Slice;
use slint::platform::software_renderer::{MinimalSoftwareWindow, RepaintBufferType, Rgb565Pixel};
use slint::platform::{Platform, PlatformError, WindowAdapter};
use slint::PhysicalSize;

pub const WIDTH: u32 = 96;
pub const HEIGHT: u32 = 32;

/// The one pixel size this probe font is rasterised at — matches the
/// `font-size: 16px;` set on the probe's `Text` element below, so
/// `PixelFont::scale_delta` is exactly 1:1 (no interpolation rounding to
/// account for).
const PROBE_PX: i16 = 16;

// `x`/`y` bearing is `(0, 0)` for both glyphs: per
// `firmware/gen_emoji_font.c`'s documented convention
// (`y = (bitmap_top - height) * 64`), a glyph whose top sits exactly at the
// ascent line (`bitmap_top == height == ascent`) has `y = 0` — the simplest
// placement, and exactly matches this font's `ascent: PROBE_PX as f32`.
// Byte-array literals are inlined directly (rvalue-static promotion),
// mirroring `gen_emoji_font.c`'s own generated-code shape
// (`BitmapGlyph { .., data: Slice::from_slice(&[<bytes>]) }`) rather than
// naming a separate `static` for each — `const`s referencing `static`s by
// address is unnecessary complexity this rig doesn't need.
//
// glyph_index 0 = heart (fully opaque), 1 = marker `'X'` (half-opaque —
// deliberately a DIFFERENT alpha than the heart glyph, so a pixel scan can
// tell the two glyphs apart by blended color alone; see module doc). Order
// here is independent of CHAR_MAP's order below (CHAR_MAP must be
// codepoint-sorted for `PixelFont::shape_text`'s binary search; this array
// need not be).
static GLYPHS_16: [BitmapGlyph; 2] = [
    BitmapGlyph {
        x: 0,
        y: 0,
        width: PROBE_PX,
        height: PROBE_PX,
        x_advance: PROBE_PX * 64,
        data: Slice::from_slice(&[0xFFu8; (PROBE_PX * PROBE_PX) as usize]),
    },
    BitmapGlyph {
        x: 0,
        y: 0,
        width: PROBE_PX,
        height: PROBE_PX,
        x_advance: PROBE_PX * 64,
        data: Slice::from_slice(&[0x80u8; (PROBE_PX * PROBE_PX) as usize]),
    },
];

static GLYPH_SETS: [BitmapGlyphs; 1] = [BitmapGlyphs {
    pixel_size: PROBE_PX,
    glyph_data: Slice::from_slice(&GLYPHS_16),
}];

// Codepoint-sorted: 'X' (U+0058 = 88) < '❤' (U+2764 = 10084). Deliberately
// carries NO entry for VS16 (U+FE0F) — mirrors the real bundled font's gap
// (see module doc and `protocol::emoji`'s module doc).
static CHAR_MAP: [CharacterMapEntry; 2] = [
    CharacterMapEntry {
        code_point: 'X',
        glyph_index: 1,
    },
    CharacterMapEntry {
        code_point: '\u{2764}',
        glyph_index: 0,
    },
];

static PROBE_FONT: BitmapFont = BitmapFont {
    family_name: Slice::from_slice(b"EmojiBlankCellProbe"),
    character_map: Slice::from_slice(&CHAR_MAP),
    units_per_em: PROBE_PX as f32,
    ascent: PROBE_PX as f32,
    descent: 0.0,
    x_height: (PROBE_PX / 2) as f32,
    cap_height: (PROBE_PX * 3 / 4) as f32,
    glyphs: Slice::from_slice(&GLYPH_SETS),
    weight: 400,
    italic: false,
    sdf: false,
};

slint::slint! {
    export component EmojiBlankCellProbeUi inherits Window {
        width: 96px;
        height: 32px;
        background: #000000;

        in property <string> line;

        // No `font-family:` set — same as every dynamic message-body `Text`
        // in the real screens (`message_view.rs`'s `MessageBubble`): the
        // globally-registered `BitmapFont` (registered BEFORE this
        // component is constructed — see `EmojiBlankCellProbeFrame::new`)
        // is what actually serves this run at render time, exactly the
        // mechanism `firmware/src/ui/platform.rs`'s `emoji_font` module doc
        // documents ("resolves EVERY text run ... to it").
        Text {
            text: line;
            font-size: 16px;
            color: #ffffff;
            x: 0px;
            y: 0px;
        }
    }
}

struct EmojiBlankCellProbePlatform {
    window: Rc<MinimalSoftwareWindow>,
    start: Instant,
}

impl Platform for EmojiBlankCellProbePlatform {
    fn create_window_adapter(&self) -> Result<Rc<dyn WindowAdapter>, PlatformError> {
        Ok(self.window.clone())
    }

    fn duration_since_start(&self) -> Duration {
        self.start.elapsed()
    }
}

/// Render rig for the emoji blank-cell probe.
///
/// # Panics
/// Panics if a Slint platform is already installed in this process — see
/// `message_view_promo.rs`'s identical note. Callers must ensure exactly one
/// [`EmojiBlankCellProbeFrame::new`] runs per process.
pub struct EmojiBlankCellProbeFrame {
    window: Rc<MinimalSoftwareWindow>,
    ui: EmojiBlankCellProbeUi,
}

impl EmojiBlankCellProbeFrame {
    pub fn new() -> Self {
        let window = MinimalSoftwareWindow::new(RepaintBufferType::ReusedBuffer);
        window.set_size(PhysicalSize::new(WIDTH, HEIGHT));
        slint::platform::set_platform(Box::new(EmojiBlankCellProbePlatform {
            window: window.clone(),
            start: Instant::now(),
        }))
        .expect("Slint platform already set in this process");

        // Register the probe font BEFORE component init — same sequencing
        // `TDeckPlatform::install()` documents as REQUIRED (platform.rs),
        // not incidental: it's what makes this the font every text run in
        // this component resolves to.
        window.renderer().register_bitmap_font(&PROBE_FONT);

        let ui = EmojiBlankCellProbeUi::new().expect("EmojiBlankCellProbeUi::new");
        ui.show().expect("EmojiBlankCellProbeUi::show");

        EmojiBlankCellProbeFrame { window, ui }
    }

    /// Set the probe `Text`'s content directly — no normalization applied
    /// here; callers decide whether to pass raw wire text or
    /// `protocol::emoji::normalize_inbound`'s output (see the test module).
    pub fn set_line(&self, line: &str) {
        self.ui.set_line(line.into());
    }

    /// Render one frame.
    pub fn render(&self) -> Vec<Rgb565Pixel> {
        slint::platform::update_timers_and_animations();
        self.window.request_redraw();

        let mut framebuffer = vec![Rgb565Pixel(0); (WIDTH * HEIGHT) as usize];
        let rendered = self.window.draw_if_needed(|renderer| {
            renderer.render(&mut framebuffer, WIDTH as usize);
        });
        assert!(
            rendered,
            "emoji blank-cell probe frame was not dirty — nothing painted"
        );
        framebuffer
    }
}

impl Default for EmojiBlankCellProbeFrame {
    fn default() -> Self {
        Self::new()
    }
}

/// Convert a rendered RGB565 framebuffer to an `image::RgbImage` (RGB8) —
/// same conversion every other `ui_sim` render module duplicates locally.
pub fn framebuffer_to_rgb_image(
    framebuffer: &[Rgb565Pixel],
    width: u32,
    height: u32,
) -> image::RgbImage {
    let mut img = image::RgbImage::new(width, height);
    for (i, px) in framebuffer.iter().enumerate() {
        let r5 = (px.0 >> 11) & 0x1F;
        let g6 = (px.0 >> 5) & 0x3F;
        let b5 = px.0 & 0x1F;
        let r8 = ((r5 << 3) | (r5 >> 2)) as u8;
        let g8 = ((g6 << 2) | (g6 >> 4)) as u8;
        let b8 = ((b5 << 3) | (b5 >> 2)) as u8;
        let x = (i as u32) % width;
        let y = (i as u32) / width;
        img.put_pixel(x, y, image::Rgb([r8, g8, b8]));
    }
    img
}

/// What a probe-frame column looks like: no glyph painted anywhere in it
/// (the "blank cell" defect), the heart glyph (opaque), or the `X` marker
/// glyph (half-opaque) — see module doc for why these two are distinguished
/// by alpha rather than hue.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum ColumnKind {
    Blank,
    Heart,
    Marker,
}

/// Classify column `x` of `img` by scanning every row: the probe's glyphs
/// never overlap in `x`, so at most one glyph kind can paint any given
/// column, and a fully-black column (background never touched) is `Blank`.
pub fn classify_column(img: &image::RgbImage, x: u32, height: u32) -> ColumnKind {
    for y in 0..height {
        let px = img.get_pixel(x, y);
        let (r, g, b) = (px[0], px[1], px[2]);
        if (r, g, b) != (0, 0, 0) {
            // Heart = alpha 0xFF blended with white text on black
            // background = (255,255,255). Marker = alpha 0x80 blended =
            // roughly (128,128,128) — well below the heart's full-white
            // brightness either way.
            return if r > 200 {
                ColumnKind::Heart
            } else {
                ColumnKind::Marker
            };
        }
    }
    ColumnKind::Blank
}
