// SPDX-License-Identifier: GPL-3.0-only
//! Generates the FALLBACK asset path's RGB565 byte array at build time.
//!
//! This is the host-
//! runnable proof that the design plan's fallback mechanism — "build.rs
//! generates an RGB565 byte array (exactly the shape gen_emoji_font.c
//! already uses for fonts) fed to Image::from_rgb8 / SharedPixelBuffer at
//! runtime" — actually works, exercised independently of the PRIMARY
//! `@image-url` + `SLINT_EMBED_RESOURCES=embed-for-software-renderer` path
//! (which `firmware/src/ui/screens/unprovisioned.rs` ships).
//!
//! Unlike `gen_emoji_font.c` (which shells out to a compiled C/FreeType host
//! tool because it rasterises TEXT), this generator computes its pixel data
//! directly in Rust — no external tool, no input asset file — because the
//! fallback's whole premise is "no runtime image decoder needed on-target";
//! proving that premise only requires *some* build-time-computed pixel
//! array, not specifically a PNG-decode step (the PRIMARY path already
//! proves the PNG-decode-at-build-time half). A small procedural "moon"
//! disc (in the widened palette's `moon-silver` / `space-deep` tones) is
//! good enough to prove the mechanism end-to-end and to be visually
//! distinguishable in the host-sim render from the two `@image-url` assets
//! next to it.
//!
//! Output: `$OUT_DIR/fallback_image.rs`, `include!`-d by `src/lib.rs`.
//! Emits packed `u16` RGB565 words (2 bytes/pixel, matching the design
//! plan's flash-cost table for this option) rather than pre-expanded RGB8 —
//! `src/lib.rs` unpacks each word into a `SharedPixelBuffer<Rgb8Pixel>` at
//! runtime, exactly the shape the plan describes ("fed to Image::from_rgb8
//! / SharedPixelBuffer at runtime").

use std::env;
use std::fmt::Write as _;
use std::path::PathBuf;

const SIZE: usize = 24;

// Widened-palette hex twins (must match firmware/src/ui/theme.slint's
// `moon-silver` / `space-deep` tokens exactly — generator input only, not a
// runtime dependency on that file).
const MOON_SILVER: (u8, u8, u8) = (0xc8, 0xd0, 0xe0);
const SPACE_DEEP: (u8, u8, u8) = (0x07, 0x0a, 0x12);

const fn rgb565(r8: u8, g8: u8, b8: u8) -> u16 {
    let r5 = (r8 >> 3) as u16;
    let g6 = (g8 >> 2) as u16;
    let b5 = (b8 >> 3) as u16;
    (r5 << 11) | (g6 << 5) | b5
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_rs = out_dir.join("fallback_image.rs");

    let cx = (SIZE as f32 - 1.0) / 2.0;
    let cy = (SIZE as f32 - 1.0) / 2.0;
    let r = SIZE as f32 / 2.0 - 1.0;

    let moon = rgb565(MOON_SILVER.0, MOON_SILVER.1, MOON_SILVER.2);
    let bg = rgb565(SPACE_DEEP.0, SPACE_DEEP.1, SPACE_DEEP.2);

    let mut words = Vec::with_capacity(SIZE * SIZE);
    for y in 0..SIZE {
        for x in 0..SIZE {
            let dx = x as f32 - cx;
            let dy = y as f32 - cy;
            let word = if dx * dx + dy * dy <= r * r { moon } else { bg };
            words.push(word);
        }
    }

    let mut src = String::new();
    writeln!(src, "// Generated by ui_sim/build.rs — DO NOT EDIT.").unwrap();
    writeln!(src, "pub const FALLBACK_WIDTH: usize = {SIZE};").unwrap();
    writeln!(src, "pub const FALLBACK_HEIGHT: usize = {SIZE};").unwrap();
    writeln!(src, "pub const FALLBACK_RGB565: [u16; {}] = [", SIZE * SIZE).unwrap();
    for chunk in words.chunks(12) {
        let line: Vec<String> = chunk.iter().map(|w| format!("0x{w:04x}")).collect();
        writeln!(src, "    {},", line.join(", ")).unwrap();
    }
    writeln!(src, "];").unwrap();

    std::fs::write(&out_rs, src).expect("write fallback_image.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
