#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# scripts/sync-cargo-lock-versions.test.sh — smoke test for
# scripts/sync-cargo-lock-versions.sh.
#
# Builds a minimal fake workspace (root + a "firmware" detached workspace,
# each with a Cargo.toml and a hand-written Cargo.lock) in a throwaway
# tmpdir, so this never touches the real repo's lockfiles. Exercises: the
# happy-path bump, idempotency (a second run is a no-op), and the two
# fail-loud guards (a missing [[package]] entry, and refusing to touch a
# registry package that happens to share a target name).
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
sync="${script_dir}/sync-cargo-lock-versions.sh"

tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

write_fixture() {
  local root="$1" version="$2"
  mkdir -p "${root}/protocol" "${root}/host" "${root}/firmware"

  cat >"${root}/Cargo.toml" <<EOF
[workspace]
members = ["protocol", "host"]

[workspace.package]
version = "${version}"
EOF

  cat >"${root}/protocol/Cargo.toml" <<'EOF'
[package]
name = "protocol"
version.workspace = true
EOF

  cat >"${root}/host/Cargo.toml" <<'EOF'
[package]
name = "host"
version.workspace = true
EOF

  cat >"${root}/firmware/Cargo.toml" <<EOF
[package]
name = "firmware"
version = "${version}"
EOF

  # Root Cargo.lock: two local workspace members (no source= line) plus one
  # unrelated registry dependency, deliberately at the SAME version string,
  # to prove the substitution is scoped by name+stanza, not a blind global
  # version replace.
  cat >"${root}/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "protocol"
version = "0.1.0"
dependencies = [
 "anyhow",
]

[[package]]
name = "host"
version = "0.1.0"
dependencies = [
 "protocol",
]

[[package]]
name = "anyhow"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
EOF

  # firmware/Cargo.lock: firmware's own entry plus the path-crossed
  # "protocol" entry.
  cat >"${root}/firmware/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "firmware"
version = "0.1.0"
dependencies = [
 "protocol",
]

[[package]]
name = "protocol"
version = "0.1.0"
dependencies = [
 "anyhow",
]
EOF
}

# --- Case 1: happy path — bump 0.1.0 -> 0.2.0, only the local entries move.
fixture="${tmpdir}/case1"
write_fixture "${fixture}" "0.1.0"
sed -i 's/version = "0.1.0"/version = "0.2.0"/' "${fixture}/Cargo.toml"
sed -i 's/version = "0.1.0"/version = "0.2.0"/' "${fixture}/firmware/Cargo.toml"

(cd "${fixture}" && "${sync}") >"${tmpdir}/case1.log" 2>&1 || {
  echo "FAIL: expected the happy-path sync to succeed" >&2
  cat "${tmpdir}/case1.log" >&2
  exit 1
}

if [[ "$(sed -n '/name = "protocol"/{n;p}' "${fixture}/Cargo.lock")" != 'version = "0.2.0"' ]]; then
  echo "FAIL: expected root Cargo.lock's protocol entry to move to 0.2.0" >&2
  exit 1
fi
if [[ "$(sed -n '/name = "host"/{n;p}' "${fixture}/Cargo.lock")" != 'version = "0.2.0"' ]]; then
  echo "FAIL: expected root Cargo.lock's host entry to move to 0.2.0" >&2
  exit 1
fi
if [[ "$(sed -n '/name = "anyhow"/{n;p}' "${fixture}/Cargo.lock")" != 'version = "0.1.0"' ]]; then
  echo "FAIL: expected the unrelated registry dependency \"anyhow\" to be left untouched" >&2
  exit 1
fi
if [[ "$(sed -n '/name = "firmware"/{n;p}' "${fixture}/firmware/Cargo.lock")" != 'version = "0.2.0"' ]]; then
  echo "FAIL: expected firmware/Cargo.lock's firmware entry to move to 0.2.0" >&2
  exit 1
fi
if [[ "$(sed -n '/name = "protocol"/{n;p}' "${fixture}/firmware/Cargo.lock")" != 'version = "0.2.0"' ]]; then
  echo "FAIL: expected firmware/Cargo.lock's path-crossed protocol entry to move to 0.2.0" >&2
  exit 1
fi

# --- Case 2: idempotency — a second run makes no further changes and still
# exits 0.
before_root="$(cat "${fixture}/Cargo.lock")"
before_fw="$(cat "${fixture}/firmware/Cargo.lock")"
(cd "${fixture}" && "${sync}") >"${tmpdir}/case1-rerun.log" 2>&1 || {
  echo "FAIL: expected an already-in-sync rerun to still exit 0" >&2
  cat "${tmpdir}/case1-rerun.log" >&2
  exit 1
}
if [[ "$(cat "${fixture}/Cargo.lock")" != "${before_root}" || "$(cat "${fixture}/firmware/Cargo.lock")" != "${before_fw}" ]]; then
  echo "FAIL: expected a rerun with nothing to sync to leave both lockfiles byte-identical" >&2
  exit 1
fi
if ! grep -q "already in sync" "${tmpdir}/case1-rerun.log"; then
  echo "FAIL: expected the rerun to report it found nothing to sync" >&2
  cat "${tmpdir}/case1-rerun.log" >&2
  exit 1
fi

# --- Case 3: fail loud when a workspace member has no matching
# [[package]] entry in Cargo.lock (e.g. the lockfile is missing a crate
# entirely).
fixture="${tmpdir}/case3"
write_fixture "${fixture}" "0.1.0"
sed -i 's/version = "0.1.0"/version = "0.2.0"/' "${fixture}/Cargo.toml"
sed -i '/name = "host"/,+3d' "${fixture}/Cargo.lock"
if (cd "${fixture}" && "${sync}") >"${tmpdir}/case3.log" 2>&1; then
  echo "FAIL: expected sync to fail when a workspace member has no Cargo.lock entry" >&2
  cat "${tmpdir}/case3.log" >&2
  exit 1
fi
if ! grep -q 'no \[\[package\]\] entry named "host"' "${tmpdir}/case3.log"; then
  echo "FAIL: expected a clear error naming the missing entry" >&2
  cat "${tmpdir}/case3.log" >&2
  exit 1
fi

# --- Case 4: refuse to touch a same-named registry package (defensive
# source= guard) instead of silently mis-patching it.
fixture="${tmpdir}/case4"
write_fixture "${fixture}" "0.1.0"
sed -i 's/version = "0.1.0"/version = "0.2.0"/' "${fixture}/Cargo.toml"
# Make "host" look like a registry package by giving it a source= line.
sed -i '/name = "host"/,/version = "0.1.0"/ s/version = "0.1.0"/version = "0.1.0"\nsource = "registry+https:\/\/github.com\/rust-lang\/crates.io-index"/' "${fixture}/Cargo.lock"
if (cd "${fixture}" && "${sync}") >"${tmpdir}/case4.log" 2>&1; then
  echo "FAIL: expected sync to refuse a same-named entry carrying a source= line" >&2
  cat "${tmpdir}/case4.log" >&2
  exit 1
fi
if ! grep -q 'registry package, not a local workspace member' "${tmpdir}/case4.log"; then
  echo "FAIL: expected a clear error about the registry-package guard" >&2
  cat "${tmpdir}/case4.log" >&2
  exit 1
fi

echo "sync-cargo-lock-versions.test.sh: all cases passed"
